function q(id, category, difficulty, prompt, options, correctIndex) {
  return {
    questionId: id,
    category,
    difficulty,
    prompt,
    options: options.map((text, i) => ({ optionId: `${id}-o${i + 1}`, text })),
    correctOptionId: `${id}-o${correctIndex}`,
    activeStatus: true,
  };
}

const QUESTIONS = [
  q("q001", "Science", "easy", "What gas do plants absorb from the air during photosynthesis?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 3),
  q("q002", "Science", "easy", "How many planets are in our solar system?", ["7", "8", "9", "10"], 2),
  q("q003", "Science", "medium", "What is the chemical symbol for gold?", ["Go", "Gd", "Au", "Ag"], 3),
  q("q004", "Science", "medium", "Which part of the cell contains genetic material?", ["Mitochondria", "Nucleus", "Ribosome", "Cytoplasm"], 2),
  q("q005", "Science", "hard", "What is the approximate speed of light in vacuum?", ["300,000 km/s", "150,000 km/s", "3,000 km/s", "30,000 km/s"], 1),
  q("q006", "Science", "easy", "Water boils at what temperature at sea level?", ["90°C", "100°C", "110°C", "120°C"], 2),
  q("q007", "History", "easy", "Who was the first President of the United States?", ["Abraham Lincoln", "Thomas Jefferson", "George Washington", "John Adams"], 3),
  q("q008", "History", "medium", "In which year did World War II end?", ["1943", "1944", "1945", "1946"], 3),
  q("q009", "History", "medium", "The Great Wall of China was built primarily to defend against which group?", ["Mongols", "Romans", "Persians", "Vikings"], 1),
  q("q010", "History", "easy", "Ancient Egyptian rulers were known as:", ["Emperors", "Pharaohs", "Sultans", "Czars"], 2),
  q("q011", "History", "hard", "Which empire was ruled by Suleiman the Magnificent?", ["Roman", "Ottoman", "Mughal", "Byzantine"], 2),
  q("q012", "History", "medium", "The Renaissance began in which country?", ["France", "Spain", "Italy", "England"], 3),
  q("q013", "Geography", "easy", "What is the largest ocean on Earth?", ["Atlantic", "Indian", "Arctic", "Pacific"], 4),
  q("q014", "Geography", "easy", "Which continent is the Sahara Desert mainly in?", ["Asia", "Africa", "Australia", "South America"], 2),
  q("q015", "Geography", "medium", "What is the capital of Japan?", ["Osaka", "Kyoto", "Tokyo", "Nagoya"], 3),
  q("q016", "Geography", "medium", "Which river is the longest in the world?", ["Amazon", "Nile", "Yangtze", "Mississippi"], 2),
  q("q017", "Geography", "hard", "Mount Kilimanjaro is located in which country?", ["Kenya", "Tanzania", "Ethiopia", "Uganda"], 2),
  q("q018", "Geography", "easy", "How many continents are there?", ["5", "6", "7", "8"], 3),
  q("q019", "General Knowledge", "easy", "How many days are in a leap year?", ["364", "365", "366", "367"], 3),
  q("q020", "General Knowledge", "easy", "What is the smallest prime number?", ["0", "1", "2", "3"], 3),
  q("q021", "General Knowledge", "medium", "How many keys are on a standard piano?", ["76", "88", "92", "100"], 2),
  q("q022", "General Knowledge", "medium", "What is the main ingredient in traditional hummus?", ["Lentils", "Chickpeas", "Peas", "Beans"], 2),
  q("q023", "General Knowledge", "hard", "Which language has the most native speakers worldwide?", ["English", "Spanish", "Hindi", "Mandarin Chinese"], 4),
  q("q024", "Technology", "easy", "What does CPU stand for?", ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Utility"], 1),
  q("q025", "Technology", "easy", "Which company created the iPhone?", ["Google", "Microsoft", "Apple", "Samsung"], 3),
  q("q026", "Technology", "medium", "What does HTTPS add compared to HTTP?", ["Speed", "Encryption", "Images", "Compression"], 2),
  q("q027", "Technology", "medium", "Which of these is a programming language?", ["HTML Color", "Python", "Wi-Fi", "Bluetooth"], 2),
  q("q028", "Technology", "hard", "What does GPU typically stand for?", ["General Processing Unit", "Graphics Processing Unit", "Global Program Utility", "Graphic Performance Utility"], 2),
  q("q029", "Nature", "easy", "Which animal is known as the king of the jungle?", ["Tiger", "Lion", "Leopard", "Cheetah"], 2),
  q("q030", "Nature", "easy", "What do bees collect from flowers to make honey?", ["Dew", "Pollen and nectar", "Sap", "Seeds"], 2),
  q("q031", "Nature", "medium", "A group of wolves is called a:", ["Herd", "Pack", "Flock", "School"], 2),
  q("q032", "Nature", "medium", "Which tree is known for producing acorns?", ["Maple", "Pine", "Oak", "Birch"], 3),
  q("q033", "Nature", "hard", "What is the tallest type of tree in the world?", ["Redwood", "Baobab", "Oak", "Eucalyptus"], 1),
  q("q034", "Space", "easy", "Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Mercury"], 2),
  q("q035", "Space", "easy", "The Moon orbits which body?", ["The Sun", "Mars", "Earth", "Venus"], 3),
  q("q036", "Space", "medium", "Which planet has the most prominent rings?", ["Jupiter", "Uranus", "Neptune", "Saturn"], 4),
  q("q037", "Space", "medium", "What is a light-year a measure of?", ["Time", "Distance", "Brightness", "Speed"], 2),
  q("q038", "Space", "hard", "Which dwarf planet was reclassified from planet status in 2006?", ["Ceres", "Eris", "Pluto", "Haumea"], 3),
  q("q039", "Entertainment", "easy", "Which instrument has 88 keys?", ["Guitar", "Violin", "Piano", "Flute"], 3),
  q("q040", "Entertainment", "easy", "How many strings does a standard guitar usually have?", ["4", "5", "6", "8"], 3),
  q("q041", "Entertainment", "medium", "Who painted the Mona Lisa?", ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], 3),
  q("q042", "Entertainment", "medium", "A haiku traditionally has how many syllables in total?", ["10", "12", "17", "21"], 3),
  q("q043", "Entertainment", "hard", "Which Shakespeare play features the characters Rosencrantz and Guildenstern?", ["Macbeth", "Hamlet", "Othello", "King Lear"], 2),
  q("q044", "Problem Solving", "easy", "If you have 3 apples and give 1 away, how many remain?", ["1", "2", "3", "4"], 2),
  q("q045", "Problem Solving", "medium", "A baker needs 20 minutes per cake and has 3 cakes. If they bake one at a time, how long in total?", ["20 min", "40 min", "60 min", "80 min"], 3),
  q("q046", "Problem Solving", "medium", "You see a boat filled with people, yet there isn’t a single person on board. How?", ["They are all couples", "They are all married", "The boat is empty", "They are all underwater"], 2),
  q("q047", "Problem Solving", "hard", "A clock shows 3:15. What is the angle between hour and minute hands?", ["0°", "7.5°", "15°", "22.5°"], 2),
  q("q048", "Logical Reasoning", "easy", "Which number comes next: 2, 4, 6, 8, …?", ["9", "10", "12", "14"], 2),
  q("q049", "Logical Reasoning", "easy", "All roses are flowers. This is a rose. Therefore it is a:", ["Tree", "Flower", "Weed", "Vegetable"], 2),
  q("q050", "Logical Reasoning", "medium", "If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely:", ["Razzies only", "Lazzies", "Neither", "Unknown"], 2),
  q("q051", "Logical Reasoning", "medium", "Find the odd one out: circle, square, triangle, cube", ["Circle", "Square", "Triangle", "Cube"], 4),
  q("q052", "Logical Reasoning", "hard", "A is taller than B. B is taller than C. Who is shortest?", ["A", "B", "C", "Cannot tell"], 3),
  q("q053", "Basic Mathematics", "easy", "What is 7 × 8?", ["54", "56", "63", "72"], 2),
  q("q054", "Basic Mathematics", "easy", "What is 15% of 200?", ["20", "25", "30", "35"], 3),
  q("q055", "Basic Mathematics", "medium", "What is the square root of 144?", ["11", "12", "13", "14"], 2),
  q("q056", "Basic Mathematics", "medium", "If a triangle has angles 90° and 45°, the third angle is:", ["35°", "45°", "55°", "60°"], 2),
  q("q057", "Basic Mathematics", "hard", "What is 2 to the power of 8?", ["128", "256", "512", "64"], 2),
  q("q058", "Puzzles", "easy", "I have keys but no locks. I have space but no room. What am I?", ["A piano", "A keyboard", "A map", "A house"], 2),
  q("q059", "Puzzles", "medium", "What gets wetter the more it dries?", ["A sponge", "A towel", "Soap", "Rain"], 2),
  q("q060", "Puzzles", "medium", "The more you take, the more you leave behind. What are they?", ["Footsteps", "Memories", "Coins", "Breaths"], 1),
  q("q061", "Puzzles", "hard", "I speak without a mouth and hear without ears. What am I?", ["A phone", "An echo", "A radio", "The wind"], 2),
  q("q062", "Human Body", "easy", "How many bones are in the adult human body?", ["186", "206", "226", "300"], 2),
  q("q063", "Human Body", "easy", "Which organ pumps blood throughout the body?", ["Lungs", "Liver", "Heart", "Kidney"], 3),
  q("q064", "Human Body", "medium", "Which vitamin is primarily produced when skin is exposed to sunlight?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], 3),
  q("q065", "Human Body", "medium", "The funny bone is actually a:", ["Bone", "Nerve", "Muscle", "Tendon"], 2),
  q("q066", "Human Body", "hard", "How many chambers does the human heart have?", ["2", "3", "4", "5"], 3),
  q("q067", "World Facts", "easy", "Which country is both a continent and a country?", ["India", "Australia", "Brazil", "Canada"], 2),
  q("q068", "World Facts", "medium", "Which country has the most time zones?", ["USA", "Russia", "France", "China"], 3),
  q("q069", "World Facts", "medium", "The currency of Japan is the:", ["Yuan", "Won", "Yen", "Ringgit"], 3),
  q("q070", "World Facts", "hard", "Which city is known as the City of Canals?", ["Amsterdam", "Venice", "Bruges", "Bangkok"], 2),
  q("q071", "Culture", "easy", "Diwali is widely known as the festival of:", ["Colors", "Lights", "Harvest", "Water"], 2),
  q("q072", "Culture", "easy", "Sushi originated in which country?", ["China", "Korea", "Japan", "Thailand"], 3),
  q("q073", "Culture", "medium", "Flamenco is a traditional dance from:", ["Italy", "Spain", "Greece", "Portugal"], 2),
  q("q074", "Culture", "medium", "The Taj Mahal is located in:", ["Delhi", "Jaipur", "Agra", "Mumbai"], 3),
  q("q075", "Culture", "hard", "Which instrument is central to a traditional Scottish bagpipe band?", ["Harp", "Great Highland bagpipe", "Lute", "Cello"], 2),
  q("q076", "Science", "medium", "What is H2O more commonly known as?", ["Salt", "Water", "Oxygen", "Hydrogen peroxide"], 2),
  q("q077", "Geography", "easy", "The equator divides Earth into:", ["East and West", "North and South", "Land and sea", "Day and night"], 2),
  q("q078", "Space", "easy", "The Sun is a:", ["Planet", "Star", "Moon", "Comet"], 2),
  q("q079", "General Knowledge", "easy", "How many hours are in a day?", ["12", "20", "24", "48"], 3),
  q("q080", "Technology", "easy", "What does WWW stand for?", ["World Wide Web", "Wide World Web", "Web World Wide", "Wireless Web World"], 1),
  q("q081", "Nature", "easy", "Penguins are birds that:", ["Fly long distances", "Cannot fly", "Live only in the Arctic", "Hibernate in trees"], 2),
  q("q082", "Entertainment", "easy", "How many minutes are in one hour?", ["30", "45", "60", "90"], 3),
  q("q083", "Basic Mathematics", "easy", "What is 9 + 10?", ["18", "19", "20", "21"], 2),
  q("q084", "World Facts", "easy", "Which is the largest country by land area?", ["Canada", "China", "USA", "Russia"], 4),
  q("q085", "Human Body", "easy", "People typically have how many fingers on both hands combined?", ["8", "10", "12", "20"], 2),
  q("q086", "History", "easy", "The Olympic Games originated in:", ["Rome", "Egypt", "Greece", "China"], 3),
  q("q087", "Science", "medium", "Earth’s atmosphere is mostly:", ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"], 3),
  q("q088", "Geography", "medium", "Which US city is nicknamed the Big Apple?", ["Los Angeles", "Chicago", "New York City", "Boston"], 3),
  q("q089", "Puzzles", "easy", "What has a head and a tail but no body?", ["A coin", "A snake", "A comet", "A kite"], 1),
  q("q090", "Logical Reasoning", "easy", "If yesterday was Monday, what is tomorrow?", ["Tuesday", "Wednesday", "Thursday", "Sunday"], 2),
];

function c(id, gameMode, intensityLevel, challengeType, title, instruction, extra = {}) {
  return {
    challengeId: id,
    gameMode,
    challengeType,
    title,
    instruction,
    intensityLevel,
    category: extra.category || "connection",
    estimatedDurationSec: extra.duration || 45,
    requiresResponse: !!extra.requiresResponse,
    requiresPhysicalAction: extra.requiresPhysicalAction !== false,
    requiresDescription: !!extra.requiresDescription,
    skipAllowed: true,
    replacementAllowed: true,
    activeStatus: true,
    sourceType: "SYSTEM_GENERATED",
  };
}

const CHALLENGES = [
  c("c001", "LOVE_MAKING", "soft", "Couple Conversation", "Grateful minute", "Sit facing each other. Take turns naming one thing you are grateful for about your partner. Keep it specific and kind."),
  c("c002", "LOVE_MAKING", "soft", "Perform", "Hand hold", "Hold both of your partner’s hands for 30 seconds. Keep eye contact and smile — no phones."),
  c("c003", "LOVE_MAKING", "soft", "Describe", "First spark", "Describe the moment you knew you liked your partner. Speak for at least 20 seconds.", { requiresDescription: true, requiresResponse: true, requiresPhysicalAction: false }),
  c("c004", "LOVE_MAKING", "soft", "Partner Prompt", "Compliment shower", "Give your partner three genuine compliments: one about character, one about a habit, one about how they make you feel."),
  c("c005", "LOVE_MAKING", "soft", "Answer", "Favorite ordinary day", "Ask: “What ordinary day with me would you happily repeat forever?” Listen fully, then answer the same question.", { requiresResponse: true, requiresPhysicalAction: false }),
  c("c006", "LOVE_MAKING", "soft", "Perform", "Forehead rest", "Rest your foreheads together and breathe slowly together for 20 seconds."),
  c("c007", "LOVE_MAKING", "soft", "Choose", "Playlist of us", "Together, pick three songs that feel like “us.” Hum a few bars of one."),
  c("c008", "LOVE_MAKING", "soft", "Improvise", "Thank-you toast", "Make a 15-second toast thanking your partner for something small they did recently."),
  c("c009", "LOVE_MAKING", "soft", "Couple Conversation", "Safe harbor", "Share one way your partner makes you feel safe. Then switch."),
  c("c010", "LOVE_MAKING", "soft", "Perform", "Gentle cheek kiss", "Place a light kiss on your partner’s cheek and say one kind sentence."),
  c("c011", "LOVE_MAKING", "playful", "Perform", "Slow sway", "Stand up and slow-dance for 30 seconds, even without music. Laugh if you step on toes."),
  c("c012", "LOVE_MAKING", "playful", "Improvise", "Movie trailer", "Act out a 20-second trailer for a movie about your relationship. Overact freely."),
  c("c013", "LOVE_MAKING", "playful", "Partner Prompt", "Secret handshake", "Invent a 4-step couple handshake and perform it twice."),
  c("c014", "LOVE_MAKING", "playful", "Describe", "Nickname origin", "Invent (or retell) a sweet nickname for your partner and explain why it fits.", { requiresDescription: true, requiresResponse: true, requiresPhysicalAction: false }),
  c("c015", "LOVE_MAKING", "playful", "Perform", "Feed a bite", "If you have a snack or sip nearby, feed or offer it to your partner. If not, mime it with extra drama."),
  c("c016", "LOVE_MAKING", "playful", "Choose", "Date reroll", "Each propose a tiny date idea for this week. Coin-flip or choose one to actually plan."),
  c("c017", "LOVE_MAKING", "playful", "Couple Conversation", "Embarrassing crush", "Share a harmless, funny crush-era story from before you met. Keep it light."),
  c("c018", "LOVE_MAKING", "playful", "Perform", "Piggyback promise", "Give a 10-second hug from behind (a gentle squeeze) and whisper a silly promise."),
  c("c019", "LOVE_MAKING", "playful", "Answer", "Superpower swap", "If your partner had one superpower in daily life, what should it be and why?", { requiresResponse: true, requiresPhysicalAction: false }),
  c("c020", "LOVE_MAKING", "playful", "Improvise", "Love advert", "Film-free: perform a 15-second commercial selling “being this couple.”"),
  c("c021", "LOVE_MAKING", "intimate", "Perform", "Breathing hug", "Share a full hug for 40 seconds. Match your breathing. No talking."),
  c("c022", "LOVE_MAKING", "intimate", "Perform", "Hand massage", "Give your partner a one-minute hand or shoulder massage. Ask what pressure feels good."),
  c("c023", "LOVE_MAKING", "intimate", "Partner Prompt", "Whispered wish", "Whisper one thing you’d love to do together in the next seven days, close to their ear."),
  c("c024", "LOVE_MAKING", "intimate", "Couple Conversation", "I feel closest when", "Complete the sentence: “I feel closest to you when…” Both answer."),
  c("c025", "LOVE_MAKING", "intimate", "Perform", "Slow kiss", "Share a slow, unhurried kiss (as you both prefer). Pause afterward and smile."),
  c("c026", "LOVE_MAKING", "intimate", "Describe", "Home in you", "Describe how your partner’s presence feels like home. Speak slowly.", { requiresDescription: true, requiresResponse: true, requiresPhysicalAction: false }),
  c("c027", "LOVE_MAKING", "intimate", "Perform", "Forehead kiss ritual", "Kiss your partner’s forehead, then their temple, then hold their face gently for a few seconds."),
  c("c028", "LOVE_MAKING", "intimate", "Answer", "Need of the night", "Ask: “What would make you feel most cared for right now?” Then do one small thing toward it if you can.", { requiresResponse: true }),
  c("c029", "LOVE_MAKING", "intimate", "Choose", "Lights low", "Dim a light or put phones face-down. Sit close, knees touching, for 45 seconds of quiet."),
  c("c030", "LOVE_MAKING", "intimate", "Improvise", "Love letter aloud", "Speak a 4-sentence love letter as if writing it. Your partner just receives it."),
  c("c031", "ROLEPLAY", "soft", "Roleplay", "Café strangers", "You are two strangers who just sat at the same café table. Introduce yourselves and find one thing in common."),
  c("c032", "ROLEPLAY", "soft", "Roleplay", "Magazine interview", "One of you is a journalist. Interview your partner about “a quietly remarkable person.” Switch after 30 seconds."),
  c("c033", "ROLEPLAY", "soft", "Roleplay", "Lost tourists", "You are tourists who just got lost. Together, invent a charming city and ask a passerby (the room) for directions."),
  c("c034", "ROLEPLAY", "soft", "Improvise", "Weather report", "Deliver a 20-second weather report about the “climate” of your relationship today."),
  c("c035", "ROLEPLAY", "soft", "Describe", "New names", "Pick character names. Tell each other who you are in one sentence, then greet in character.", { requiresDescription: true, requiresResponse: true, requiresPhysicalAction: false }),
  c("c036", "ROLEPLAY", "soft", "Couple Conversation", "Time travelers", "You just arrived from 50 years in the future. What one kind thing do you tell your past selves?"),
  c("c037", "ROLEPLAY", "soft", "Choose", "Bookstore meet-cute", "You reach for the same book. Decide which book it is, then act the awkward-then-sweet moment."),
  c("c038", "ROLEPLAY", "soft", "Partner Prompt", "Royal court", "One is a monarch, one is an advisor. The advisor must recommend a kind decree for the kingdom (your home)."),
  c("c039", "ROLEPLAY", "soft", "Answer", "Pen pals", "You have been pen pals for a year and are meeting for the first time. What do you say first?", { requiresResponse: true, requiresPhysicalAction: false }),
  c("c040", "ROLEPLAY", "soft", "Perform", "Ballroom bow", "Bow or curtsy, take both hands, and take four slow dance steps in character as elegant guests."),
  c("c041", "ROLEPLAY", "playful", "Roleplay", "Secret agents", "You are partners on a mission to retrieve “the last cookie.” Plan the heist in dramatic whispers."),
  c("c042", "ROLEPLAY", "playful", "Roleplay", "Cooking show", "Host a 30-second cooking show using any object nearby as a “mystery ingredient.”"),
  c("c043", "ROLEPLAY", "playful", "Improvise", "Sports commentators", "Commentate your partner walking across the room as if it is an Olympic event."),
  c("c044", "ROLEPLAY", "playful", "Roleplay", "Rival bakers", "You own rival bakeries on the same street. Negotiate a truce over an imaginary croissant."),
  c("c045", "ROLEPLAY", "playful", "Partner Prompt", "Director’s take", "One is a film director. Give your star (your partner) notes for a romantic scene that is only a hug and a line."),
  c("c046", "ROLEPLAY", "playful", "Choose", "Fantasy jobs", "Each pick a fantasy job (dragon librarian, cloud gardener). Pitch why you’d hire the other."),
  c("c047", "ROLEPLAY", "playful", "Describe", "Talking cats", "You are very dignified cats who have just knocked over a vase. Explain yourselves.", { requiresDescription: true, requiresResponse: true, requiresPhysicalAction: false }),
  c("c048", "ROLEPLAY", "playful", "Perform", "Award speech", "Accept a fake award for “Best Partner in a Leading Role.” Thank your co-star."),
  c("c049", "ROLEPLAY", "playful", "Roleplay", "Space captains", "Your starship has stalled. Argue, then agree, on whether to ask the nearest planet for tea."),
  c("c050", "ROLEPLAY", "playful", "Improvise", "Radio hosts", "Co-host a 20-second late-night radio show called “Soft Landing.”"),
  c("c051", "ROLEPLAY", "intimate", "Roleplay", "Rainy balcony", "You are a couple on a balcony after rain. One offers a coat (or a sweater). Exchange two sincere lines."),
  c("c052", "ROLEPLAY", "intimate", "Roleplay", "Letters across a war", "You are reunited after a long time apart. First words only — then a long hug."),
  c("c053", "ROLEPLAY", "intimate", "Partner Prompt", "Wedding toast (private)", "Give a short toast as if you are marrying each other again tomorrow. Keep it private and warm."),
  c("c054", "ROLEPLAY", "intimate", "Roleplay", "Old souls", "You have been together for 40 years in this scene. Sit close and recall “the day we met” as those future selves."),
  c("c055", "ROLEPLAY", "intimate", "Describe", "Safe house", "You have found shelter together. Describe the room you would build for the two of you.", { requiresDescription: true, requiresResponse: true, requiresPhysicalAction: false }),
  c("c056", "ROLEPLAY", "intimate", "Perform", "Slow dance, no music", "In character as longtime lovers at a quiet party, slow-dance for 40 seconds."),
  c("c057", "ROLEPLAY", "intimate", "Couple Conversation", "Lighthouse keepers", "You keep a lighthouse together. Tell your partner why you trust them with the night watch."),
  c("c058", "ROLEPLAY", "intimate", "Roleplay", "First dance redo", "Re-enact a first dance as if you already know you will choose each other. One dip is optional."),
  c("c059", "ROLEPLAY", "intimate", "Answer", "Vow draft", "In character, complete: “I choose you because…” Your partner answers in character too.", { requiresResponse: true, requiresPhysicalAction: false }),
  c("c060", "ROLEPLAY", "intimate", "Improvise", "Midnight kitchen", "You meet in the kitchen at midnight. Steal a quiet kiss (if you both want) and share a secret smile."),
];

const GAME_MODES = [
  {
    modeId: "LOVE_MAKING",
    name: "Love Making",
    tagline: "Closer, slower, sweeter",
    description: "Light trivia with paired, optional closeness — compliments, touch, and tender conversation. Always skippable.",
  },
  {
    modeId: "ROLEPLAY",
    name: "Roleplay",
    tagline: "A scene, just for two",
    description: "Knowledge rounds mixed with short, tasteful scenes you improvise together. Continuity can build across the night.",
  },
];

const INTENSITY_LEVELS = [
  { id: "soft", name: "Soft", description: "Warm, gentle, low-pressure connection." },
  { id: "playful", name: "Playful", description: "Flirty, fun, a little theatrical." },
  { id: "intimate", name: "Intimate", description: "Closer touch and quieter emotion — never explicit." },
];

const SCORING_CONFIG = {
  correctPoints: 10,
  speedBonusEnabled: false,
  difficultyBonusEnabled: false,
  streakBonusEnabled: false,
};

const PROFANITY = [
  "fuck", "shit", "bitch", "asshole", "bastard", "dick", "cunt", "slut", "whore", "nigger", "faggot",
];

module.exports = {
  QUESTIONS,
  CHALLENGES,
  GAME_MODES,
  INTENSITY_LEVELS,
  SCORING_CONFIG,
  PROFANITY,
};
